version: "3.9"

services:
  db:
    image: postgres:16
    container_name: insighthub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: insighthub_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: insighthub_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/insighthub_db
      ENV: production
      SECRET_KEY: supersecretkey123
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data: